"""
Seed script to populate the database with 50+ AI applications.
Run: python scripts/seed_applications.py
"""

import sys
from pathlib import Path
from datetime import datetime
from decimal import Decimal

sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy.orm import Session
from app.database import SessionLocal, engine
from app.models import AIApplication, RiskLevel, Base
import uuid

# Sample applications data
APPLICATIONS = [
    # GENERAL AI - 10 apps
    {
        "name": "ChatGPT",
        "vendor": "OpenAI",
        "category": "General AI",
        "description": "Advanced conversational AI model for text generation and analysis",
        "risk_score": 65,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 70,
        "security_score": 65,
        "data_handling_score": 60,
        "enterprise_control_score": 60,
        "integration_score": 85,
        "permission_score": 70,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US, EU",
        "authentication": ["API Key", "OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Popular general-purpose LLM. Data retention policies updated regularly."
    },
    {
        "name": "Claude",
        "vendor": "Anthropic",
        "category": "General AI",
        "description": "Constitutional AI assistant focused on harmlessness and helpfulness",
        "risk_score": 55,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 75,
        "security_score": 80,
        "data_handling_score": 75,
        "enterprise_control_score": 70,
        "integration_score": 80,
        "permission_score": 80,
        "mcp_support": True,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Focus on constitutional AI principles and safety."
    },
    {
        "name": "Google Gemini",
        "vendor": "Google",
        "category": "General AI",
        "description": "Multimodal AI model supporting text, images, and code",
        "risk_score": 60,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 65,
        "security_score": 75,
        "data_handling_score": 65,
        "enterprise_control_score": 75,
        "integration_score": 85,
        "permission_score": 70,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US, EU, Multi-region",
        "authentication": ["API Key", "OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Google's multimodal model with enterprise options."
    },
    {
        "name": "Microsoft Copilot",
        "vendor": "Microsoft",
        "category": "General AI",
        "description": "AI assistant integrated with Microsoft ecosystem",
        "risk_score": 62,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 68,
        "security_score": 75,
        "data_handling_score": 65,
        "enterprise_control_score": 85,
        "integration_score": 90,
        "permission_score": 75,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region",
        "authentication": ["Enterprise SSO", "OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Strong enterprise integration with Microsoft 365."
    },
    {
        "name": "Perplexity AI",
        "vendor": "Perplexity",
        "category": "General AI",
        "description": "Research-focused AI with real-time web search capabilities",
        "risk_score": 58,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 72,
        "security_score": 70,
        "data_handling_score": 68,
        "enterprise_control_score": 55,
        "integration_score": 75,
        "permission_score": 68,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Focus on information retrieval with web search."
    },
    {
        "name": "Grok",
        "vendor": "xAI",
        "category": "General AI",
        "description": "Real-time AI with access to X (Twitter) platform data",
        "risk_score": 72,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 55,
        "security_score": 65,
        "data_handling_score": 50,
        "enterprise_control_score": 45,
        "integration_score": 70,
        "permission_score": 55,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Real-time access to X platform presents data privacy concerns."
    },
    {
        "name": "DeepSeek",
        "vendor": "DeepSeek",
        "category": "General AI",
        "description": "Open-source language model with competitive performance",
        "risk_score": 50,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 80,
        "security_score": 75,
        "data_handling_score": 85,
        "enterprise_control_score": 80,
        "integration_score": 70,
        "permission_score": 85,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "China",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open source but data residency in China. Review data protection requirements."
    },
    {
        "name": "LLaMA 2/3",
        "vendor": "Meta",
        "category": "General AI",
        "description": "Open-source large language model family",
        "risk_score": 45,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 85,
        "security_score": 80,
        "data_handling_score": 90,
        "enterprise_control_score": 85,
        "integration_score": 75,
        "permission_score": 90,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open source with full control when self-hosted."
    },
    {
        "name": "Qwen",
        "vendor": "Alibaba",
        "category": "General AI",
        "description": "Chinese language-optimized large language model",
        "risk_score": 55,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 70,
        "security_score": 72,
        "data_handling_score": 68,
        "enterprise_control_score": 75,
        "integration_score": 70,
        "permission_score": 72,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "China",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Alibaba model with China data residency."
    },
    {
        "name": "Mistral AI",
        "vendor": "Mistral",
        "category": "General AI",
        "description": "Efficient open-source model optimized for deployment",
        "risk_score": 48,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 82,
        "security_score": 78,
        "data_handling_score": 85,
        "enterprise_control_score": 80,
        "integration_score": 75,
        "permission_score": 85,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "EU",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: European-based open source model with strong privacy focus."
    },

    # AI CODING - 10 apps
    {
        "name": "GitHub Copilot",
        "vendor": "GitHub/Microsoft",
        "category": "AI Coding",
        "description": "AI-powered code completion and generation integrated with GitHub",
        "risk_score": 68,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 65,
        "security_score": 70,
        "data_handling_score": 60,
        "enterprise_control_score": 85,
        "integration_score": 95,
        "permission_score": 75,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US, EU options",
        "authentication": ["GitHub OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Wide adoption but data training practices merit review."
    },
    {
        "name": "Cursor",
        "vendor": "Cursor",
        "category": "AI Coding",
        "description": "VS Code fork with integrated AI assistant for code editing",
        "risk_score": 55,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 75,
        "security_score": 75,
        "data_handling_score": 70,
        "enterprise_control_score": 70,
        "integration_score": 85,
        "permission_score": 78,
        "mcp_support": True,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Privacy-focused coding assistant with MCP support."
    },
    {
        "name": "Claude for Code",
        "vendor": "Anthropic",
        "category": "AI Coding",
        "description": "Claude API optimized for code generation and analysis",
        "risk_score": 52,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 80,
        "security_score": 85,
        "data_handling_score": 80,
        "enterprise_control_score": 75,
        "integration_score": 80,
        "permission_score": 85,
        "mcp_support": True,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Strong code understanding with safety guarantees."
    },
    {
        "name": "Windsurf",
        "vendor": "Codeium",
        "category": "AI Coding",
        "description": "AI code editor with advanced code intelligence",
        "risk_score": 54,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 78,
        "security_score": 76,
        "data_handling_score": 75,
        "enterprise_control_score": 70,
        "integration_score": 82,
        "permission_score": 80,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Codeium's advanced code editor with enterprise features."
    },
    {
        "name": "Amazon Q Developer",
        "vendor": "Amazon AWS",
        "category": "AI Coding",
        "description": "AWS native AI coding assistant with IDE integration",
        "risk_score": 58,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 72,
        "security_score": 80,
        "data_handling_score": 70,
        "enterprise_control_score": 90,
        "integration_score": 85,
        "permission_score": 80,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region AWS",
        "authentication": ["AWS IAM"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Strong enterprise integration with AWS services."
    },
    {
        "name": "Codeium",
        "vendor": "Codeium",
        "category": "AI Coding",
        "description": "Free AI code completion with privacy focus",
        "risk_score": 48,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 85,
        "security_score": 82,
        "data_handling_score": 85,
        "enterprise_control_score": 75,
        "integration_score": 80,
        "permission_score": 88,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Privacy-first free code completion tool."
    },
    {
        "name": "Tabnine",
        "vendor": "Tabnine",
        "category": "AI Coding",
        "description": "AI code completions with local and cloud options",
        "risk_score": 50,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 85,
        "security_score": 80,
        "data_handling_score": 85,
        "enterprise_control_score": 80,
        "integration_score": 85,
        "permission_score": 85,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Local/US/EU options",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Offers local deployment option for privacy."
    },
    {
        "name": "Continue.dev",
        "vendor": "Continue",
        "category": "AI Coding",
        "description": "Open-source AI assistant for VS Code and JetBrains IDEs",
        "risk_score": 45,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 88,
        "security_score": 85,
        "data_handling_score": 90,
        "enterprise_control_score": 80,
        "integration_score": 85,
        "permission_score": 90,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open source with full privacy control."
    },
    {
        "name": "Phind",
        "vendor": "Phind",
        "category": "AI Coding",
        "description": "AI assistant specialized in programming tasks",
        "risk_score": 56,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 74,
        "security_score": 76,
        "data_handling_score": 72,
        "enterprise_control_score": 68,
        "integration_score": 78,
        "permission_score": 75,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Programming-focused assistant."
    },

    # ENTERPRISE AI - 8 apps
    {
        "name": "Azure OpenAI Service",
        "vendor": "Microsoft Azure",
        "category": "Enterprise AI",
        "description": "Enterprise-grade OpenAI models hosted on Azure infrastructure",
        "risk_score": 52,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 78,
        "security_score": 88,
        "data_handling_score": 80,
        "enterprise_control_score": 95,
        "integration_score": 90,
        "permission_score": 85,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region, EU options",
        "authentication": ["Enterprise SSO", "API Key"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Enterprise Azure deployment with strong controls."
    },
    {
        "name": "Amazon Bedrock",
        "vendor": "Amazon AWS",
        "category": "Enterprise AI",
        "description": "Fully managed service providing access to foundational models",
        "risk_score": 50,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 80,
        "security_score": 88,
        "data_handling_score": 85,
        "enterprise_control_score": 92,
        "integration_score": 88,
        "permission_score": 88,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region AWS",
        "authentication": ["AWS IAM"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: AWS managed service with strong enterprise controls."
    },
    {
        "name": "Google Vertex AI",
        "vendor": "Google Cloud",
        "category": "Enterprise AI",
        "description": "Google's unified AI platform for building and deploying ML models",
        "risk_score": 55,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 76,
        "security_score": 86,
        "data_handling_score": 78,
        "enterprise_control_score": 90,
        "integration_score": 87,
        "permission_score": 85,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region, EU options",
        "authentication": ["Google Cloud IAM"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Google Cloud native ML platform."
    },
    {
        "name": "IBM watsonx",
        "vendor": "IBM",
        "category": "Enterprise AI",
        "description": "Enterprise AI and data platform for business applications",
        "risk_score": 54,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 80,
        "security_score": 87,
        "data_handling_score": 82,
        "enterprise_control_score": 93,
        "integration_score": 85,
        "permission_score": 86,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region, On-premise options",
        "authentication": ["Enterprise SSO"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: IBM's enterprise AI platform with strong governance."
    },
    {
        "name": "Oracle AI Platform",
        "vendor": "Oracle",
        "category": "Enterprise AI",
        "description": "Integrated AI capabilities within Oracle Cloud Infrastructure",
        "risk_score": 56,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 78,
        "security_score": 86,
        "data_handling_score": 80,
        "enterprise_control_score": 91,
        "integration_score": 84,
        "permission_score": 84,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region, On-premise options",
        "authentication": ["Enterprise IAM"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Oracle's cloud-based AI platform."
    },
    {
        "name": "SAP Joule",
        "vendor": "SAP",
        "category": "Enterprise AI",
        "description": "AI copilot integrated with SAP enterprise applications",
        "risk_score": 58,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 76,
        "security_score": 85,
        "data_handling_score": 78,
        "enterprise_control_score": 92,
        "integration_score": 93,
        "permission_score": 85,
        "mcp_support": False,
        "api_available": False,
        "data_residency": "Multi-region, On-premise",
        "authentication": ["SAP SSO"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: SAP native AI integration for ERP systems."
    },
    {
        "name": "Salesforce Einstein",
        "vendor": "Salesforce",
        "category": "Enterprise AI",
        "description": "AI-powered CRM assistant integrated with Salesforce platform",
        "risk_score": 60,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 74,
        "security_score": 84,
        "data_handling_score": 76,
        "enterprise_control_score": 90,
        "integration_score": 95,
        "permission_score": 80,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region",
        "authentication": ["Salesforce OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Salesforce CRM AI assistant with customer data considerations."
    },

    # PRODUCTIVITY AI - 8 apps
    {
        "name": "Notion AI",
        "vendor": "Notion",
        "category": "Productivity AI",
        "description": "AI assistance integrated within Notion workspace",
        "risk_score": 62,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 68,
        "security_score": 75,
        "data_handling_score": 65,
        "enterprise_control_score": 75,
        "integration_score": 95,
        "permission_score": 70,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US/EU",
        "authentication": ["Notion OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: AI processing of workspace content data."
    },
    {
        "name": "Grammarly",
        "vendor": "Grammarly",
        "category": "Productivity AI",
        "description": "AI-powered writing assistant for grammar, tone, and clarity",
        "risk_score": 68,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 62,
        "security_score": 72,
        "data_handling_score": 58,
        "enterprise_control_score": 75,
        "integration_score": 85,
        "permission_score": 65,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Wide browser/app integration means extensive text exposure."
    },
    {
        "name": "Canva AI",
        "vendor": "Canva",
        "category": "Productivity AI",
        "description": "AI design assistant within Canva platform",
        "risk_score": 64,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 65,
        "security_score": 73,
        "data_handling_score": 62,
        "enterprise_control_score": 70,
        "integration_score": 90,
        "permission_score": 68,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Global",
        "authentication": ["OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Design content data processing considerations."
    },
    {
        "name": "Adobe Firefly",
        "vendor": "Adobe",
        "category": "Productivity AI",
        "description": "Generative AI for creative assets within Adobe Creative Cloud",
        "risk_score": 60,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 70,
        "security_score": 78,
        "data_handling_score": 68,
        "enterprise_control_score": 82,
        "integration_score": 92,
        "permission_score": 75,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Multi-region",
        "authentication": ["Adobe SSO"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Adobe Creative Cloud integration with content generation."
    },
    {
        "name": "Jasper AI",
        "vendor": "Jasper",
        "category": "Productivity AI",
        "description": "AI content generation platform for marketing copy",
        "risk_score": 62,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 68,
        "security_score": 75,
        "data_handling_score": 65,
        "enterprise_control_score": 75,
        "integration_score": 80,
        "permission_score": 70,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Marketing content generation with brand data handling."
    },
    {
        "name": "Copy.ai",
        "vendor": "Copy.ai",
        "category": "Productivity AI",
        "description": "AI copywriting assistant for various content types",
        "risk_score": 58,
        "risk_level": RiskLevel.MEDIUM,
        "privacy_score": 72,
        "security_score": 74,
        "data_handling_score": 70,
        "enterprise_control_score": 70,
        "integration_score": 78,
        "permission_score": 72,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Cloud-based copywriting with content processing."
    },
    {
        "name": "Microsoft Copilot Pro",
        "vendor": "Microsoft",
        "category": "Productivity AI",
        "description": "Enhanced Copilot experience with advanced reasoning",
        "risk_score": 61,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 69,
        "security_score": 76,
        "data_handling_score": 67,
        "enterprise_control_score": 78,
        "integration_score": 88,
        "permission_score": 72,
        "mcp_support": False,
        "api_available": False,
        "data_residency": "Multi-region",
        "authentication": ["Microsoft SSO"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Premium Microsoft AI assistant tier."
    },

    # AI AUTOMATION - 5 apps
    {
        "name": "n8n",
        "vendor": "n8n",
        "category": "AI Automation",
        "description": "Open-source workflow automation platform with AI capabilities",
        "risk_score": 48,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 85,
        "security_score": 82,
        "data_handling_score": 85,
        "enterprise_control_score": 85,
        "integration_score": 90,
        "permission_score": 88,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open-source with self-hosting option for privacy."
    },
    {
        "name": "Zapier AI",
        "vendor": "Zapier",
        "category": "AI Automation",
        "description": "AI automation of business processes across 5000+ apps",
        "risk_score": 65,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 64,
        "security_score": 76,
        "data_handling_score": 60,
        "enterprise_control_score": 80,
        "integration_score": 98,
        "permission_score": 68,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US",
        "authentication": ["OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Wide integration means data flows through Zapier."
    },
    {
        "name": "Make.com",
        "vendor": "Make",
        "category": "AI Automation",
        "description": "Visual workflow builder with AI-powered automation",
        "risk_score": 64,
        "risk_level": RiskLevel.HIGH,
        "privacy_score": 65,
        "security_score": 75,
        "data_handling_score": 62,
        "enterprise_control_score": 78,
        "integration_score": 92,
        "permission_score": 70,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "US/EU",
        "authentication": ["OAuth"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Workflow automation with multi-app data handling."
    },
    {
        "name": "Dify",
        "vendor": "Dify",
        "category": "AI Automation",
        "description": "Open-source LLM application platform for automation",
        "risk_score": 45,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 88,
        "security_score": 85,
        "data_handling_score": 90,
        "enterprise_control_score": 85,
        "integration_score": 75,
        "permission_score": 90,
        "mcp_support": True,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open-source with full control and MCP support."
    },
    {
        "name": "LangChain",
        "vendor": "LangChain",
        "category": "AI Automation",
        "description": "Framework for developing AI applications with language models",
        "risk_score": 40,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 90,
        "security_score": 88,
        "data_handling_score": 92,
        "enterprise_control_score": 90,
        "integration_score": 85,
        "permission_score": 95,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open-source framework for custom AI development."
    },

    # AI INFRASTRUCTURE - 7 apps
    {
        "name": "LangGraph",
        "vendor": "LangChain",
        "category": "AI Infrastructure",
        "description": "State machine framework for building agent workflows",
        "risk_score": 38,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 92,
        "security_score": 89,
        "data_handling_score": 94,
        "enterprise_control_score": 88,
        "integration_score": 80,
        "permission_score": 96,
        "mcp_support": True,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Developer framework for agent infrastructure."
    },
    {
        "name": "LlamaIndex",
        "vendor": "LlamaIndex",
        "category": "AI Infrastructure",
        "description": "Data framework for LLM applications",
        "risk_score": 42,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 89,
        "security_score": 87,
        "data_handling_score": 90,
        "enterprise_control_score": 85,
        "integration_score": 82,
        "permission_score": 92,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open-source data indexing for LLMs."
    },
    {
        "name": "CrewAI",
        "vendor": "CrewAI",
        "category": "AI Infrastructure",
        "description": "Framework for orchestrating AI agents",
        "risk_score": 40,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 91,
        "security_score": 88,
        "data_handling_score": 92,
        "enterprise_control_score": 85,
        "integration_score": 78,
        "permission_score": 94,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open-source agent orchestration framework."
    },
    {
        "name": "AutoGen",
        "vendor": "Microsoft",
        "category": "AI Infrastructure",
        "description": "Framework for building AI agents with conversational capabilities",
        "risk_score": 42,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 90,
        "security_score": 87,
        "data_handling_score": 91,
        "enterprise_control_score": 86,
        "integration_score": 79,
        "permission_score": 93,
        "mcp_support": True,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Microsoft's open-source agent framework."
    },
    {
        "name": "Llama 3 Inference",
        "vendor": "Meta",
        "category": "AI Infrastructure",
        "description": "Open model optimized for inference and deployment",
        "risk_score": 35,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 95,
        "security_score": 92,
        "data_handling_score": 96,
        "enterprise_control_score": 92,
        "integration_score": 85,
        "permission_score": 98,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Meta's open model with full privacy when self-hosted."
    },
    {
        "name": "Mistral Models",
        "vendor": "Mistral AI",
        "category": "AI Infrastructure",
        "description": "Open-source models family for various sizes and tasks",
        "risk_score": 38,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 93,
        "security_score": 90,
        "data_handling_score": 94,
        "enterprise_control_score": 89,
        "integration_score": 83,
        "permission_score": 96,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted or EU",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: European open-source model options."
    },
    {
        "name": "vLLM",
        "vendor": "vLLM",
        "category": "AI Infrastructure",
        "description": "High-throughput LLM serving engine",
        "risk_score": 32,
        "risk_level": RiskLevel.LOW,
        "privacy_score": 96,
        "security_score": 93,
        "data_handling_score": 97,
        "enterprise_control_score": 91,
        "integration_score": 80,
        "permission_score": 99,
        "mcp_support": False,
        "api_available": True,
        "data_residency": "Self-hosted",
        "authentication": ["Self-managed"],
        "is_demo": True,
        "notes": "DEMO ASSESSMENT: Open-source inference engine for maximum control."
    },
]


def seed_applications(db: Session):
    """Seed the database with AI applications."""

    # Check if applications already exist
    existing_count = db.query(AIApplication).count()
    if existing_count > 0:
        print(f"Database already contains {existing_count} applications. Skipping seed.")
        return

    applications = []
    for app_data in APPLICATIONS:
        app = AIApplication(
            id=str(uuid.uuid4()),
            name=app_data["name"],
            vendor=app_data["vendor"],
            category=app_data["category"],
            description=app_data["description"],
            risk_score=Decimal(str(app_data["risk_score"])),
            risk_level=app_data["risk_level"],
            privacy_score=Decimal(str(app_data["privacy_score"])),
            security_score=Decimal(str(app_data["security_score"])),
            data_handling_score=Decimal(str(app_data["data_handling_score"])),
            enterprise_control_score=Decimal(str(app_data["enterprise_control_score"])),
            integration_score=Decimal(str(app_data["integration_score"])),
            permission_score=Decimal(str(app_data["permission_score"])),
            mcp_support=app_data["mcp_support"],
            api_available=app_data["api_available"],
            data_residency=app_data.get("data_residency"),
            authentication=app_data.get("authentication", []),
            is_demo=app_data.get("is_demo", True),
            notes=app_data.get("notes"),
            last_assessed=datetime.now(),
            enterprise_controls={
                "data_retention": "Check vendor policy",
                "sso_support": app_data.get("authentication", []),
                "audit_logs": "Vendor dependent"
            }
        )
        applications.append(app)

    db.add_all(applications)
    db.commit()

    print(f"✓ Successfully seeded {len(applications)} AI applications!")

    # Print summary by category
    categories = db.query(
        AIApplication.category,
        func.count(AIApplication.id)
    ).group_by(AIApplication.category).all()

    print("\nApplications by category:")
    for category, count in categories:
        print(f"  - {category}: {count}")


if __name__ == "__main__":
    db = SessionLocal()
    try:
        seed_applications(db)
        print("\n✓ Database seeding complete!")
    except Exception as e:
        print(f"✗ Error seeding database: {e}")
        db.rollback()
    finally:
        db.close()
